/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jc.model;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import javax.swing.JOptionPane;
import javax.swing.*;
//import org.jvnet.substance.*;
//import org.jvnet.substance.watermark.*;
/**
 *
 * @author Samanta
 */
public class welcome extends javax.swing.JFrame {

    
int posxInicial;
int posY;
    public welcome() {
        initComponents();
        setLocationRelativeTo(this);
     posxInicial=    welcome.getX();
    posY=welcome.getY();
    
        Thread t1=new Thread(new Runnable() {
            @Override
            public void run() {
     while(true){
         try{
             welcome.setLocation(posxInicial, posY);
             Thread.sleep(10);
             posxInicial=posxInicial+1;
             if(posxInicial>=390)posxInicial=0;
         }catch(Exception e){
             
         }
     }
            }
        });
        t1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWelcome = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        jLabellinea1 = new javax.swing.JLabel();
        jLabellinea2 = new javax.swing.JLabel();
        jLabellinea3 = new javax.swing.JLabel();
        botonUsuarioReg = new javax.swing.JButton();
        botonUsuarioNoReg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(204, 153, 0));
        welcome.setText("WELCOME");

        jLabellinea1.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabellinea1.setForeground(new java.awt.Color(204, 153, 0));
        jLabellinea1.setText("Este es un  sistema diseñado para el procesamiento en tiempo real.");

        jLabellinea2.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabellinea2.setForeground(new java.awt.Color(204, 153, 0));
        jLabellinea2.setText("Por lo tanto le permitirá realizar consultas, actualizaciones, borrado ");

        jLabellinea3.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jLabellinea3.setForeground(new java.awt.Color(204, 153, 0));
        jLabellinea3.setText("e ingreso de información a la Base de Datos Etihad Airways");

        botonUsuarioReg.setText("INGRESAR");
        botonUsuarioReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioRegActionPerformed(evt);
            }
        });

        botonUsuarioNoReg.setText("REGISTRARSE");
        botonUsuarioNoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioNoRegActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jc/model/image002.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jc/model/image001.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jc/model/logobrillante.jpg"))); // NOI18N

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWelcomeLayout.createSequentialGroup()
                        .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelWelcomeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelWelcomeLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabellinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabellinea2)
                                    .addComponent(jLabellinea3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                                .addComponent(botonUsuarioReg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(botonUsuarioNoReg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(201, 201, 201)))))
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28))
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabellinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabellinea2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabellinea3)
                        .addGap(59, 59, 59)
                        .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonUsuarioNoReg)
                                    .addComponent(botonUsuarioReg))
                                .addGap(114, 114, 114))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonUsuarioNoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioNoRegActionPerformed
        // TODO add your handling code here:
        usuariosNoRegistrados usuno=new usuariosNoRegistrados();
            usuno.pack();
            usuno.setVisible(true);
            dispose();
       /* dispose();
        //nombre de la segunda ventana
        ventana2 v2= new Ventana2();
        v2.setVisible(true);
        v2.pack();
        //regresar
        dispose();
        ventana1 v1=new ventna1();
        v1.pack();
        v1.setVisible(true);
        */
    }//GEN-LAST:event_botonUsuarioNoRegActionPerformed

    private void botonUsuarioRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioRegActionPerformed
        // TODO add your handling code here:
        usuariosRegistrados usu=new usuariosRegistrados();
            usu.pack();
            usu.setVisible(true);
            dispose();
    }//GEN-LAST:event_botonUsuarioRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
               try{
        UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"error"+ e.getMessage());
        }
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonUsuarioNoReg;
    private javax.swing.JButton botonUsuarioReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabellinea1;
    private javax.swing.JLabel jLabellinea2;
    private javax.swing.JLabel jLabellinea3;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
